//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int adm_Id { get; set; }
        public string adm_Firstname { get; set; }
        public string adm_Lastname { get; set; }
        public string adm_Contact { get; set; }
        public string adm_Email { get; set; }
        public string adm_Username { get; set; }
        public string adm_Password { get; set; }
    }
}
