//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int cust_Id { get; set; }
        public string cust_Firstname { get; set; }
        public string cust_Lastname { get; set; }
        public string cust_Contact { get; set; }
        public long cust_Cardnumber { get; set; }
        public string cust_Email { get; set; }
        public string cust_Password { get; set; }
    }
}
