//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriver
    {
        public int drv_Id { get; set; }
        public string drv_Firstname { get; set; }
        public string drv_Lastname { get; set; }
        public string drv_Contact { get; set; }
        public string drv_Location { get; set; }
        public string drv_VehicleType { get; set; }
        public string drv_Email { get; set; }
        public string drv_Password { get; set; }
    }
}
