//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder_Product
    {
        public int op_Id { get; set; }
        public int pro_Id { get; set; }
        public int ord_Id { get; set; }
    }
}
