//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEATS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbUberEatsEntities1 : DbContext
    {
        public dbUberEatsEntities1()
            : base("name=dbUberEatsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblRestuarant> tblRestuarants { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblResImage> tblResImages { get; set; }
        public virtual DbSet<tblProImage> tblProImages { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblOrder_Product> tblOrder_Product { get; set; }
        public virtual DbSet<tblDriver> tblDrivers { get; set; }
    
        public virtual ObjectResult<RestuarantsInfo_Result> RestuarantsInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RestuarantsInfo_Result>("RestuarantsInfo");
        }
    
        public virtual ObjectResult<GetRestuInfo_Result> GetRestuInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRestuInfo_Result>("GetRestuInfo");
        }
    
        public virtual ObjectResult<PicRestProcedure_Result> PicRestProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PicRestProcedure_Result>("PicRestProcedure");
        }
    
        public virtual ObjectResult<GetProduInfo_Result> GetProduInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProduInfo_Result>("GetProduInfo");
        }
    
        public virtual ObjectResult<PicProdProcedure_Result> PicProdProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PicProdProcedure_Result>("PicProdProcedure");
        }
    
        public virtual ObjectResult<GetAllOrders_Result> GetAllOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrders_Result>("GetAllOrders");
        }
    
        public virtual ObjectResult<DriverOrders_Result> DriverOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DriverOrders_Result>("DriverOrders");
        }
    
        public virtual ObjectResult<Drivers_Orders_Result> Drivers_Orders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Drivers_Orders_Result>("Drivers_Orders");
        }
    }
}
